In [2]:
import torch

In [4]:
torch.load(
    '../../experiment/vectorized-ddp-20250704-155152/checkpoint/model-best.pth',
    map_location='cuda:0',
)

OrderedDict([('module.feature_extractor.first_lin.weight',
              tensor([[ 0.0653,  0.0327, -0.0466,  ...,  0.0674, -0.0685, -0.0300],
                      [ 0.0695,  0.0136, -0.0451,  ..., -0.0141,  0.0227, -0.0135],
                      [-0.0783,  0.0114,  0.0417,  ..., -0.0530,  0.0241,  0.0245],
                      ...,
                      [-0.0573, -0.0455, -0.0665,  ...,  0.1442,  0.1277,  0.2092],
                      [ 0.0219, -0.0259,  0.0714,  ..., -0.0549,  0.0806,  0.0184],
                      [ 0.1342,  0.0238,  0.0767,  ...,  0.1186,  0.1046,  0.0401]],
                     device='cuda:0')),
             ('module.feature_extractor.first_lin.bias',
              tensor([ 0.2401, -0.0439,  0.0871, -0.0488, -0.0340,  0.0739,  0.0097,  0.1614,
                       0.0274, -0.0707, -0.0167, -0.2744, -0.0779, -0.0501, -0.0306, -0.0532,
                       0.2503, -0.0383,  0.1987, -0.0065, -0.0084,  0.0956, -0.1683,  0.0275,
                       0.0031,

In [5]:
torch.load(
    '../../experiment/vectorized-20250704-155716/checkpoint/model-best.pth',
    map_location='cuda:0',
)

OrderedDict([('feature_extractor.first_lin.weight',
              tensor([[-0.0972, -0.0327, -0.1389,  ..., -0.0654, -0.0671, -0.1211],
                      [-0.0740, -0.1012, -0.0347,  ..., -0.1398, -0.1896, -0.1915],
                      [-0.0862,  0.0389, -0.0469,  ...,  0.0324,  0.1140,  0.1751],
                      ...,
                      [-0.1034,  0.0078, -0.0192,  ..., -0.1991, -0.1736, -0.2559],
                      [ 0.0044, -0.0108,  0.0389,  ...,  0.1605,  0.1568,  0.2017],
                      [-0.0100,  0.0037, -0.0613,  ..., -0.0750,  0.0890,  0.0896]],
                     device='cuda:0')),
             ('feature_extractor.first_lin.bias',
              tensor([-0.0718,  0.1906, -0.0255,  0.0083,  0.2560, -0.0868, -0.0499,  0.1839,
                       0.0274,  0.0050,  0.0986, -0.0686, -0.1462, -0.0695, -0.0182,  0.1755,
                      -0.0991,  0.0134, -0.0599,  0.0426, -0.0287,  0.1251,  0.0141, -0.0176,
                       0.0640, -0.0435,  0.0